#!perl

sub command { NEXT }

# So you want a different beep mechanism...
#
# Don't just edit this plugin. Instead, COPY this file and add yours to
# revbank.plugins

sub hook_beep {
    my ($class) = @_;

    print "\a";
}
