#!perl

our $iban = "NL 69 ABNA 0431 1582 07";

sub hook_deposit_methods($class, $message, $hash, @) {
    $$message =  <<"END";

Please type one of the following:

'iban':      IBAN transfer ($iban)
'cash':      Cash in the cash box
'reimburse': Reimbursement of expenses agreed upon in advance
             Note: we require an invoice or receipt with this exact amount!
'other':     Provide a manual description
END

    %$hash = (
        iban => { description => "Deposit (IBAN transfer)" },
        cash => { description => "Deposit (Cash)" },
        other => { description => "Deposit (%s)", prompts => [ "Description" ] },
        reimburse => {
            description => "Reimbursement (%s, approval: %s)",
            prompts => [
                "Please provide a short description",
                "Which board member gave approval?",
            ],
        },
    );
}
