#!perl

HELP "edit" => "Edit product list";

my $filename = 'revbank.products';

sub command :Tab(edit) ($self, $cart, $command, @) {
    $command eq 'edit' or return NEXT;

    require RevBank::TextEditor;
    RevBank::TextEditor::edit($filename);
    return ACCEPT;
}
