#!perl

#Scan-foo-game for Revbank - (C)Edwin Eefting (psy0rz)

#Released under GPL or whatever revbank uses as license :)

use Time::HiRes qw( gettimeofday tv_interval);

HELP "game" => "Scan-foo game!";

my $fastest=1000;
my $fastest_name="nobody";

sub command :Tab(game) {

    my ($self, $cart, $command) = @_;

    return NEXT if $command !~ /^(?:game)$/;

    print "\nWelcome to SCAN-FOO \\o/\n";

    print "\nRecord time is $fastest by $fastest_name\n";

    my $start_time=[gettimeofday];

    for (my $i=1; $i<=5; $i++)
    {
        print "NOW SCAN game_$i: ";
        my $scanned=<STDIN>;
        if ($scanned ne "game_$i\n")
        {
            print "\nFAIL! :(  *sad trombone*\n";

            return ACCEPT;
        }
    }

    my $elapsed = tv_interval ( $start_time, [gettimeofday]);

    print "Completed in $elapsed seconds *tadaah*\n";

    if ($elapsed < $fastest)
    {
        print " #####################\n";
        print " #### NEW RECORD! ####\n";
        print " #####################\n";
        print " You did it in $elapsed !!!\n";

        print "Enter your name: ";
        $fastest_name=<STDIN>;
        $fastest=$elapsed;
    }

    return ACCEPT;
}
