=head1 NAME

products - RevBank plugin for selling products

=head1 DESCRIPTION

This plugin turns products from the product list into RevBank commands,
that add the respective products as Entries to the current Cart.

Note that by design, RevBank does not depend on this plugin or the products
list that is shared between some of the plugins. It is possible to use a
different source of products (e.g. an external database) in addition to, or
instead of, this plugin.

=head1 CONFIGURATION

See the documentation for C<RevBank::Products> (hint: in C<lib/>).
