#!perl


HELP "restart" => "Attempt to restart the RevBank shell";

sub command :Tab(restart) ($self, $cart, $command, @) {
    return NEXT if $command ne 'restart';

    call_hooks("restart_exec");
    no warnings qw(exec);
    exec $0;
    call_hooks("restart_survived");

    return ABORT, "exec() failed. You'll have to restart revbank yourself :P";
}
