#!perl

my %bounties = (
    1 => [ 10, "Bedankt voor het vegen/stofzuigen" ],
    2 => [ 10, "Bedankt voor het afvoeren van het afval" ],
    3 => [ 25, "Bedankt voor het dweilen" ],
    4 => [ 15, "Bedankt voor 't poetsen van alle tafels" ],
);

sub command :Tab(BOUNTY1,BOUNTY2,BOUNTY3,BOUNTY4) ($self, $cart, $command, @) {
    if ($command =~ /BOUNTY(\d+)/) {
        $cart
            ->add(+$bounties{$1}[0], $bounties{$1}[1])
            ->add_contra("-expenses/bounties", -$bounties{$1}[0], "$command by \$you");
        return ACCEPT;
    }

    return NEXT;
}

