#!perl

sub command { print "@_\n"; NEXT }


sub hook_user_balance($class, $username, $old, $delta, $new, @) {
    print "c: $class\n";
    print "u: $username\n";
    print "o: $old\n";
    print "d: $delta\n";
    print "n: $new\n";
}


