#!perl

HELP "<amount>" => "Withdraw or enter price manually";

sub command {
    my ($self, $cart, $command) = @_;

    my $amount = parse_amount($command);
    defined $amount or return NEXT;

    $cart->add(-$amount, "Withdrawal or unlisted product",
        { is_withdrawal => 1 });

    return ACCEPT;
}
