name: Test

on:
  push:
    branches:
      - master
      - matrixtesttest
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Standard Perl packages on ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libterm-readline-gnu-perl libcurses-ui-perl libtest2-suite-perl
      - run: prove -lv t
  test-perl-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        perl: ["5.40", "5.36", "5.34", "5.32"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libreadline-dev
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure --notest
      - run: perl -V
      - run: prove -lv t
